### ISSUE TITLE
create routing

### ISSUE THREAD

**Issue by guyanf** [ntutangyun/apollo-hd-map-viewer#1]
Hi guys.
Can I add two or more points, then create routing lines.
What can I do?

Thanks.

**Comment by ntutangyun** [comment]
Hi, you may add me on wechat for further discussion:

XX_101n374i1_XX

**Comment by ntutangyun** [comment]
This tool can only be used for viewing HD maps in apollo's protobuf format. 

Not for creating routing lines. 

For that you may need to do it using Dreamview with Apollo running.
